# Generated by Django 4.2.3 on 2023-09-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default='exist', max_length=100),
            preserve_default=False,
        ),
    ]
