# Generated by Django 4.2.3 on 2023-09-20 11:15

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_slider_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='caption',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to=firstapp.models.get_file_path),
        ),
    ]
