# Generated by Django 4.2.3 on 2023-09-20 12:07

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_rename_title_slider_caption_alter_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AddField(
            model_name='slider',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
    ]
