# Generated by Django 4.2.3 on 2023-09-20 12:22

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_slider_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
    ]
