# Generated by Django 4.2.3 on 2023-09-20 12:30

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_slider_image3_slider_image4_slider_image5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='card1',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='card2',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='card3',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='card4',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
        migrations.AddField(
            model_name='slider',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to=firstapp.models.get_file_path),
        ),
    ]
